spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  application:
    name: backend
  datasource:
    url: jdbc:postgresql://localhost:5432/gaboot
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
file:
  upload-dir: storage/
