security:
  jwt:
    secret-key: 3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b
    expiration-time: 30000
    expiration-time-refresh: 604800000 #7 days
    skip-jwt: false
spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  application:
    name: backend
# ==================== postgresql
#  datasource:
#    url: jdbc:postgresql://localhost:5432/gaboot
#    username: postgres
#    password: postgres
#    driver-class-name: org.postgresql.Driver
# ===================== mysql
  datasource:
    url: jdbc:mysql://localhost:3306/gabz
    username: root
    password: wingscorp
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
file:
  upload-dir: storage/
